export const LANGUAGE_CHOICES = [
  "Cyrodilic",
  "Nordic",
  "Aldmeri",
  "Dunmeri",
  "Bosmeri",
  "Yokudan",
  "Ta'agra",
  "Jel",
  "Orcish",
  "Nedic",
  "Ehlnofex",
  "Daedric",
  "Dovahzul",
  "Dwemeris",
  "Falmeris",
  "Reach Tongue",
  "Nibenese",
  "Colovian",
];

export const FACTION_CHOICES = [
  { id: "fighters-guild", name: "Fighters Guild" },
  { id: "mages-guild", name: "Mages Guild" },
  { id: "thieves-guild", name: "Thieves Guild" },
  { id: "dark-brotherhood", name: "Dark Brotherhood" },
  { id: "companions", name: "Companions" },
  { id: "imperial-legion", name: "Imperial Legion" },
  { id: "dawnguard", name: "Dawnguard" },
  { id: "college-of-winterhold", name: "College of Winterhold" },
  { id: "blades", name: "Blades" },
  { id: "morag-tong", name: "Morag Tong" },
  { id: "house-hlaalu", name: "House Hlaalu" },
  { id: "house-redoran", name: "House Redoran" },
  { id: "house-telvanni", name: "House Telvanni" },
  { id: "tribunal-temple", name: "Tribunal Temple" },
  { id: "penitus-oculatus", name: "Penitus Oculatus" },
];

